const HTTP_STATUS_CODE_OK = 200;
const HTTP_STATUS_CODE_CREATED = 201;
const HTTP_STATUS_CODE_UNAUTHORIZED = 401;
const HTTP_STATUS_CODE_FORBIDDEN = 403;
const HTTP_STATUS_CODE_NOT_FOUND = 404;
const HTTP_STATUS_CODE_CONFLICT = 409;

module.exports = {
    HTTP_STATUS_CODE_OK, 
    HTTP_STATUS_CODE_CREATED,
    HTTP_STATUS_CODE_UNAUTHORIZED,
    HTTP_STATUS_CODE_FORBIDDEN,
    HTTP_STATUS_CODE_CONFLICT,
}